In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [ ]:
dataset.columns

In [4]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [5]:
dependent=dataset[['charges']]

In [6]:
'''
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(independent,dependent,test_size=0.30,random_state=0)
X_train
X_test
Y_train
Y_test

          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [7]:
#but this code didnt improve the r2_score. so didnt run this while execution
'''
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]],
      shape=(936, 5))

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','linear'],
             'C':[1000,15000],
             'gamma':['auto','scale']}

grid=GridSearchCV(SVR(),param_grid,cv=3, refit=True,verbose = 3, n_jobs=-1)

grid.fit(independent,dependent)

Fitting 3 folds for each of 8 candidates, totalling 24 fits

C:\Users\subas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=3, estimator=SVR(), n_jobs=-1,
             param_grid={'C': [1000, 15000], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear']},
             verbose=3)

In [8]:
re= grid.cv_results_
#print(re)

print("R2 value for best parameter {}:".format(grid.best_params_))

R2 value for best parameter {'C': 15000, 'gamma': 'auto', 'kernel': 'linear'}:

In [9]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.118827,0.003006,0.129247,0.045474,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.090261,-0.036964,-0.131036,-0.086087,0.038518,7
1,1.000598,0.140138,0.049445,0.000803,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.674923,0.673021,0.642308,0.663417,0.014947,3
2,0.130654,0.065878,0.151884,0.016909,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.141802,-0.098386,-0.202734,-0.147641,0.042799,8
3,1.156201,0.123883,0.048314,0.001205,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.674923,0.673021,0.642308,0.663417,0.014947,3
4,0.895492,0.052581,0.171207,0.000685,15000,auto,rbf,"{'C': 15000, 'gamma': 'auto', 'kernel': 'rbf'}",0.292238,0.297380,0.307205,0.298941,0.006209,5
5,11.054936,0.645074,0.035491,0.006994,15000,auto,linear,"{'C': 15000, 'gamma': 'auto', 'kernel': 'linear'}",0.664725,0.708256,0.635073,0.669351,0.030056,1
6,0.242269,0.006372,0.172744,0.002417,15000,scale,rbf,"{'C': 15000, 'gamma': 'scale', 'kernel': 'rbf'}",0.011364,0.053215,-0.052430,0.004050,0.043438,6
7,10.985200,0.609258,0.037331,0.008081,15000,scale,linear,"{'C': 15000, 'gamma': 'scale', 'kernel': 'line...",0.664725,0.708256,0.635073,0.669351,0.030056,1

In [10]:
future_pred=grid.predict([[32,43,2,0,1]])
future_pred

C:\Users\subas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(

array([37286.23697283])