In [2]:
import pandas as pd

In [3]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [ ]:
dataset.columns

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [6]:
dependent=dataset[['charges']]

In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(independent,dependent,test_size=0.30,random_state=0)
X_train
X_test
Y_train
Y_test

          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [8]:
#but this code didnt improve the r2_score. so didnt run this while execution

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]],
      shape=(936, 5))

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],
             'C':[5,20,50,1000,15000],
             'gamma':['auto','scale']}

grid=GridSearchCV(SVR(),param_grid,cv=3, refit=True,verbose = 3, n_jobs=-1)

grid.fit(X_train,Y_train)

Fitting 3 folds for each of 40 candidates, totalling 120 fits

C:\Users\subas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=3, estimator=SVR(), n_jobs=-1,
             param_grid={'C': [5, 20, 50, 1000, 15000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [10]:
re= grid.cv_results_
#print(re)

print("R2 value for best parameter {}:".format(grid.best_params_))

R2 value for best parameter {'C': 15000, 'gamma': 'scale', 'kernel': 'rbf'}:

In [11]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.042941,0.003485,0.074311,0.010798,5,auto,rbf,"{'C': 5, 'gamma': 'auto', 'kernel': 'rbf'}",-0.021900,-0.119532,-0.106112,-0.082514,0.043210,37
1,0.050697,0.020373,0.016419,0.007735,5,auto,poly,"{'C': 5, 'gamma': 'auto', 'kernel': 'poly'}",0.002311,-0.093567,-0.080346,-0.057201,0.042426,34
2,0.085055,0.029013,0.041536,0.002591,5,auto,sigmoid,"{'C': 5, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.001903,-0.092929,-0.082571,-0.057866,0.042474,36
3,0.078415,0.005058,0.024484,0.001064,5,auto,linear,"{'C': 5, 'gamma': 'auto', 'kernel': 'linear'}",0.202654,0.090983,0.106572,0.133403,0.049379,23
4,0.095770,0.005598,0.082451,0.002195,5,scale,rbf,"{'C': 5, 'gamma': 'scale', 'kernel': 'rbf'}",-0.021862,-0.119573,-0.106118,-0.082518,0.043240,38
5,0.068328,0.002844,0.026725,0.000331,5,scale,poly,"{'C': 5, 'gamma': 'scale', 'kernel': 'poly'}",0.001644,-0.092817,-0.080240,-0.057138,0.041881,33
6,0.095171,0.006532,0.037921,0.001366,5,scale,sigmoid,"{'C': 5, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.001760,-0.092757,-0.082548,-0.057848,0.042355,35
7,0.068416,0.001146,0.026082,0.000936,5,scale,linear,"{'C': 5, 'gamma': 'scale', 'kernel': 'linear'}",0.202654,0.090983,0.106572,0.133403,0.049379,23
8,0.091092,0.001357,0.085222,0.001916,20,auto,rbf,"{'C': 20, 'gamma': 'auto', 'kernel': 'rbf'}",0.037270,-0.063253,-0.056184,-0.027389,0.045812,31
9,0.069687,0.003096,0.028102,0.000970,20,auto,poly,"{'C': 20, 'gamma': 'auto', 'kernel': 'poly'}",0.128759,0.027072,0.038797,0.064876,0.045425,28
10,0.098287,0.001789,0.038024,0.000815,20,auto,sigmoid,"{'C': 20, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.123958,0.015335,0.031821,0.057038,0.047796,30
11,0.078818,0.002747,0.025821,0.000520,20,auto,linear,"{'C': 20, 'gamma': 'auto', 'kernel': 'linear'}",0.521592,0.467085,0.455500,0.481392,0.028816,15
12,0.099362,0.003559,0.090095,0.002804,20,scale,rbf,"{'C': 20, 'gamma': 'scale', 'kernel': 'rbf'}",0.037400,-0.063376,-0.056206,-0.027394,0.045910,32
13,0.072748,0.002894,0.027751,0.000827,20,scale,poly,"{'C': 20, 'gamma': 'scale', 'kernel': 'poly'}",0.126456,0.029627,0.039173,0.065085,0.043570,27
14,0.092477,0.003244,0.037438,0.003346,20,scale,sigmoid,"{'C': 20, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.123460,0.015825,0.031905,0.057063,0.047406,29
15,0.075046,0.003470,0.024705,0.003959,20,scale,linear,"{'C': 20, 'gamma': 'scale', 'kernel': 'linear'}",0.521592,0.467085,0.455500,0.481392,0.028816,15
16,0.093991,0.002195,0.090502,0.003186,50,auto,rbf,"{'C': 50, 'gamma': 'auto', 'kernel': 'rbf'}",0.144164,0.028862,0.033492,0.068839,0.053296,25
17,0.071868,0.004646,0.027568,0.002721,50,auto,poly,"{'C': 50, 'gamma': 'auto', 'kernel': 'poly'}",0.319810,0.236302,0.228223,0.261445,0.041402,20
18,0.101041,0.002812,0.039167,0.001575,50,auto,sigmoid,"{'C': 50, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.316240,0.194085,0.207554,0.239293,0.054687,21
19,0.080752,0.008353,0.023806,0.001451,50,auto,linear,"{'C': 50, 'gamma': 'auto', 'kernel': 'linear'}",0.581754,0.549295,0.534624,0.555224,0.019692,13
20,0.095777,0.002113,0.094284,0.002270,50,scale,rbf,"{'C': 50, 'gamma': 'scale', 'kernel': 'rbf'}",0.144482,0.028562,0.033435,0.068826,0.053533,26
21,0.077589,0.004681,0.028836,0.001347,50,scale,poly,"{'C': 50, 'gamma': 'scale', 'kernel': 'poly'}",0.315373,0.241073,0.228866,0.261771,0.038229,19
22,0.102918,0.004156,0.038449,0.001483,50,scale,sigmoid,"{'C': 50, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.315466,0.194729,0.207679,0.239291,0.054122,22
23,0.087549,0.000475,0.026423,0.000987,50,scale,linear,"{'C': 50, 'gamma': 'scale', 'kernel': 'linear'}",0.581754,0.549295,0.534624,0.555224,0.019692,13
24,0.119461,0.004718,0.088738,0.002315,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.713543,0.671971,0.640038,0.675184,0.030094,7
25,0.112794,0.003439,0.026925,0.000223,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.797601,0.795391,0.764729,0.785907,0.015002,6
26,0.107922,0.002540,0.037122,0.000493,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.405221,0.336416,0.349444,0.363694,0.029842,17
27,0.104707,0.003296,0.023938,0.001153,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.663978,0.673763,0.637674,0.658471,0.015239,9
28,0.124425,0.002018,0.086103,0.002309,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.713824,0.671576,0.639937,0.675112,0.030267,8
29,0.151967,0.056868,0.027446,0.001628,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.797154,0.795738,0.764963,0.785952,0.014853,5
30,0.114536,0.003451,0.039065,0.001648,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.385746,0.319360,0.346897,0.350668,0.027233,18
31,0.113125,0.006861,0.025967,0.001843,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.663978,0.673763,0.637674,0.658471,0.015239,9
32,0.384431,0.061459,0.084620,0.000459,15000,auto,rbf,"{'C': 15000, 'gamma': 'auto', 'kernel': 'rbf'}",0.817841,0.822663,0.786739,0.809081,0.015921,2
33,1.345810,0.326441,0.029659,0.001656,15000,auto,poly,"{'C': 15000, 'gamma': 'auto', 'kernel': 'poly'}",0.828708,0.810987,0.784949,0.808215,0.017972,4
34,0.117338,0.007808,0.036624,0.001598,15000,auto,sigmoid,"{'C': 15000, 'gamma': 'auto', 'kernel': 'sigmo...",-39.833060,-43.824492,-38.789424,-40.815658,2.169808,40
35,0.433948,0.094400,0.026021,0.000759,15000,auto,linear,"{'C': 15000, 'gamma': 'auto', 'kernel': 'linear'}",0.709823,0.620585,0.632732,0.654380,0.039516,11
36,0.378016,0.054755,0.090290,0.009469,15000,scale,rbf,"{'C': 15000, 'gamma': 'scale', 'kernel': 'rbf'}",0.817899,0.822665,0.786728,0.809098,0.015937,1
37,1.282783,0.336051,0.019298,0.003804,15000,scale,poly,"{'C': 15000, 'gamma': 'scale', 'kernel': 'poly'}",0.828707,0.810987,0.784953,0.808216,0.017970,3
38,0.126370,0.010203,0.039616,0.002329,15000,scale,sigmoid,"{'C': 15000, 'gamma': 'scale', 'kernel': 'sigm...",-38.960497,-44.841158,-37.010023,-40.270559,3.328550,39
39,0.402670,0.078268,0.018516,0.003613,15000,scale,linear,"{'C': 15000, 'gamma': 'scale', 'kernel': 'line...",0.709823,0.620585,0.632732,0.654380,0.039516,11

In [11]:
future_pred=grid.predict([[32,43,2,0,1]])
future_pred

array([18115.14847727])